### ISSUE TITLE
Undetected syntax error: blank spaces between literal and langtag/datatype

### ISSUE THREAD

**Issue by cfleiner** [mmlab/TurtleValidator#16]
The syntax error of having spaces between literal and the language tag or the datatype definition is not detected. I assume that spaces are removed before the validation check as this error remains undetected.

![image](https://user-images.githubusercontent.com/75578328/171869459-ebaf0279-32f1-4093-b1f3-08ab684771b6.png)

**Comment by RubenVerborgh** [comment]
That would be in https://github.com/rdfjs/N3.js/, and I can confirm whitespace is indeed discarded.

However, https://www.w3.org/TR/turtle/#sec-grammar-ws does not give a much clearer answer so I'm hesitant to fix.

**Comment by cfleiner** [comment]
Good point. However, some parsers like the one with https://github.com/RDFLib/rdflib cannot process the mentioned issue. 

Would it be possible to add a copy button that saves the reduced version of the turtle data?
With that, the issue should be prevented for both kinds of parser implementations.

**Comment by pietercolpaert** [comment]
If you pull request it, willing to merge! Closing the issue now
